-- Enable Row Level Security (RLS) recommended for production, 
-- but for this demo we will keep it simple or enable public access.
-- Run this in the Supabase SQL Editor.

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    contact_number TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Appointments Table
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_contact TEXT REFERENCES users(contact_number),
    start_time TEXT NOT NULL, -- Storing as string for simplicity like "10:00 AM"
    status TEXT DEFAULT 'booked',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Conversations Table (for summaries)
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_contact TEXT REFERENCES users(contact_number),
    summary TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Realtime for these tables (Optional, for frontend updates)
alter publication supabase_realtime add table appointments;
alter publication supabase_realtime add table conversations;

-- --- SAMPLE DATA ---

-- Insert Users
INSERT INTO users (contact_number, name) VALUES
('+15550101', 'Alice Johnson'),
('+15550102', 'Bob Smith')
ON CONFLICT (contact_number) DO NOTHING;

-- Insert Appointments
INSERT INTO appointments (user_contact, start_time, status) VALUES
('+15550101', '10:00 AM', 'booked'),
('+15550101', '2:00 PM', 'completed'),
('+15550102', '4:30 PM', 'booked');

-- Insert Conversation History
INSERT INTO conversations (user_contact, summary) VALUES
('+15550101', 'User called to reschedule. Moved appointment to 10:00 AM.');
